---
- name: Install Docker Dependencies
  apt:
    name: "{{ docker_dependencies }}"
    update_cache: yes
- name: Add Docker GPG
  apt_key:
    ulr: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /etc/apt/keyrings/docker.gpg
- name: Add Docker Repo
  apt_repository:
    filename: docker
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
    state: present
- name: Install Docker Engine
  apt:
    name: "{{ docker_engine }}"
    update_cache: yes
