- name: Update Packages
  apt:
    update_cache: yes
    upgrade: yes
- name: Install Packages
  package:
    name: "{{ packages }}"
    state: latest
- name: Passwordless SUDO for {{ username }}
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
